apiVersion: v1
kind: Pod
metadata:
   labels:
     job: jenkins-slave
spec:
  #serviceAccount: jenkins
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: docker
      image: docker:18.06.1
      command: ["tail", "-f", "/dev/null"]
      tty: true
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
    - name: helm
      image: alpine/helm
      command: ["tail", "-f", "/dev/null"]
      tty: true
      imagePullPolicy: Always
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock